// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKv16W10nWr_QK3QIiXo4jZxwDNtLtUkM',
    appId: '1:927979576384:web:20aa5c6159a5fa282d93a5',
    messagingSenderId: '927979576384',
    projectId: 'doctor-f93b6',
    authDomain: 'doctor-f93b6.firebaseapp.com',
    storageBucket: 'doctor-f93b6.appspot.com',
    measurementId: 'G-254PZ56DT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqYIuA48OIIc-OY1QCIM_Is6FoQAK_vDg',
    appId: '1:927979576384:android:fd1b4116670d72162d93a5',
    messagingSenderId: '927979576384',
    projectId: 'doctor-f93b6',
    storageBucket: 'doctor-f93b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNqqn533gdOlLmU5gIWQgBKwUD3BYpjU',
    appId: '1:927979576384:ios:eb269c6af07797642d93a5',
    messagingSenderId: '927979576384',
    projectId: 'doctor-f93b6',
    storageBucket: 'doctor-f93b6.appspot.com',
    iosClientId: '927979576384-ea3q48qgt3kuj2uq0rj5b1n5veraj7s7.apps.googleusercontent.com',
    iosBundleId: 'com.sawafta.doctor',
  );
}
